project:
  type: website
  output-dir: docs
  preview:
    port: 7777
# metadata-files:
#   - _website.yml
#   - _format.yml

execute:
  freeze: auto

website:
  title: "A2W"
  # description: "Geoscientist Codes"
  site-url: https://ariewjy.github.io
  # site-path: "https://ariewjy.github.io/"
  # search:
  #   location: navbar
  #   type: overlay
  favicon: img/logo_rounded.png
  twitter-card:
    image: img/profile.jpg
    creator: "@Adtarie"
    card-style: summary
  open-graph: true

  navbar:
    type: light
    background: "#2D2D36"
    search: false
    pinned: false
    right:
      - text: "About"
        file: about.qmd
      - text: "Blog"
        file: index.qmd
      - text: "Publications"
        file: publications.qmd
  page-footer:
    right:
      - href: license.qmd
        text: License
    left:
      - href: https://www.quarto.org
        text: Built w/ Quarto

  page-navigation: true

format:
  html:
    theme:
      [styles.scss]
      # light: litera
      # dark: darkly
    css: styles.scss
    highlight-style: eiffel
    smooth-scroll: true
    fontsize: 1.2em
    code-link: true
    anchor-sections: true

    # table and figure setting
    tbl-cap-location: top
    fig-cap-location: top
    fig-align: center
    fig-responsive: true

    reference-location: document
    code-line-numbers: true
    code-copy: true
    code-summary: Show Code

    footnotes-hover: true
    citation: true
    appendix-style: default
    citation-location: margin
    comments:
      utterances:
        repo: ariewjy/ariewjy.github.io
