project:
  type: website
  output-dir: docs
  preview:
    port: 7777
    # browser: false
    # watch-inputs: true
    # timeout: 3600

execute:
  freeze: auto

website:
  # title: "Aditya AW"
  # description: "Geoscientist Codes"
  site-url: https://adtarie.net
  repo-url: https://github.com/ariewjy/ariewjy.github.io
  repo-actions:
    - source
    - issue
  favicon: img/logo_rounded.png
  twitter-card:
    creator: "@adtarie"
    card-style: summary_large_image
  open-graph:
    locale: en_EN
  page-navigation: true
  # google-analytics:
  # cookie-consent:
  #   type: express
  #   prefs-text: "Change Cookies 🍪"

  # search:
  #   location: navbar
  #   type: textbox

  navbar:
    type: light
    background: "#2D2D36"
    search: false
    pinned: false
    right:
      - text: "About"
        file: about.qmd
      - text: "Blog"
        file: index.qmd
      - text: "Publications"
        file: publications.qmd

  page-footer:
    right:
      - href: license.qmd
        text: License
    left:
      - href: https://www.quarto.org
        text: Built w/ Quarto

format:
  html:
    # theme: [flatly, jadey.scss] #theme inspired by https://github.com/myominnoo/myominnoo.github.io
    theme: [styles.scss]
    # light: litera
    # dark: darkly
    css: styles.scss
    toc: true
    toc-depth: 4
    highlight-style: nord
    smooth-scroll: true
    page-layout: article
    # fontsize: 1.2em
    link-external-newwindow: true
    code-link: true
    anchor-sections: true

    # table and figure setting
    tbl-cap-location: top
    fig-cap-location: top
    fig-align: center
    fig-responsive: true

    reference-location: document
    code-line-numbers: true
    code-copy: true
    code-summary: Show Code

    footnotes-hover: true
    citation: true
    appendix-style: default
    citation-location: margin
    comments:
      utterances:
        repo: ariewjy/ariewjy.github.io
